import { describe, expect, it } from "vitest";
import type { Finding, FindingId, ScanResult } from "../../packages/core/src/index.js";
import { SCAN_RESULT_SCHEMA_VERSION } from "../../packages/core/src/index.js";
import { htmlExporter, jsonExporter, sarifExporter } from "../../packages/cli/src/exporters/index.js";

const findings: readonly Finding[] = [
  {
    id: "f-1" as FindingId,
    ruleId: "security/sql-injection-raw-query",
    category: "security",
    severity: "critical",
    confidence: 0.92,
    status: "likely",
    title: "Possible SQL injection",
    description: "Untrusted input flows into a raw SQL query.",
    locations: [{ fileId: "src/db.ts" as never, path: "src/db.ts", range: { start: { offset: 10, line: 4, column: 2 }, end: { offset: 20, line: 4, column: 12 } } }],
    evidenceIds: [],
    correlatedFindingIds: [],
  },
  {
    id: "f-2" as FindingId,
    ruleId: "quality/generated-file-count",
    category: "quality",
    severity: "info",
    confidence: 1,
    status: "confirmed",
    title: "Generated file: dist/index.js",
    description: "dist/index.js was classified as generated by repository discovery.",
    locations: [{ fileId: "dist/index.js" as never, path: "dist/index.js" }],
    evidenceIds: [],
    correlatedFindingIds: [],
  },
];

const fixedResult: ScanResult = {
  schemaVersion: SCAN_RESULT_SCHEMA_VERSION,
  scan: {
    id: "scan-1" as never,
    projectId: "project-1",
    profile: "minimal",
    mode: "full",
    status: "completed",
    analyzersRun: ["security/sql-injection-raw-query", "quality/generated-file-count"],
    findingIds: findings.map((f) => f.id),
    timing: { startedAt: "2026-01-01T00:00:00.000Z", finishedAt: "2026-01-01T00:00:01.000Z", durationMs: 1000 },
  },
  findings,
  evidence: [],
  diagnostics: [],
  summary: {
    totalFindings: 2,
    findingsBySeverity: { critical: 1, info: 1 },
    findingsByCategory: { security: 1, quality: 1 },
    filesAnalyzed: 5,
    analyzersRun: ["security/sql-injection-raw-query", "quality/generated-file-count"],
  },
};

describe("jsonExporter", () => {
  it("round-trips the ScanResult exactly", () => {
    const output = jsonExporter.export(fixedResult);
    expect(JSON.parse(output)).toEqual(fixedResult);
  });
});

describe("sarifExporter", () => {
  it("produces a structurally valid SARIF 2.1.0 log for the fields we emit", () => {
    const output = sarifExporter.export(fixedResult);
    const sarif = JSON.parse(output);

    expect(sarif.version).toBe("2.1.0");
    expect(typeof sarif.$schema).toBe("string");
    expect(sarif.runs).toHaveLength(1);

    const run = sarif.runs[0];
    expect(run.tool.driver.name).toBe("code-analyzer");
    expect(run.tool.driver.rules.map((r: { id: string }) => r.id).sort()).toEqual(
      ["quality/generated-file-count", "security/sql-injection-raw-query"].sort(),
    );

    expect(run.results).toHaveLength(2);
    const [sqlResult] = run.results;
    expect(sqlResult.ruleId).toBe("security/sql-injection-raw-query");
    expect(sqlResult.level).toBe("error"); // critical -> error
    expect(sqlResult.message.text).toBe(findings[0]?.description);
    expect(sqlResult.locations[0].physicalLocation.artifactLocation.uri).toBe("src/db.ts");
    // 0-based SourcePosition.line 4 -> 1-based SARIF startLine 5
    expect(sqlResult.locations[0].physicalLocation.region.startLine).toBe(5);
    expect(sqlResult.locations[0].physicalLocation.region.startColumn).toBe(3);

    const [, infoResult] = run.results;
    expect(infoResult.level).toBe("none"); // info -> none
    expect(infoResult.locations[0].physicalLocation.region).toBeUndefined();
  });
});

describe("htmlExporter", () => {
  it("renders a self-contained page grouping findings by severity", () => {
    const output = htmlExporter.export(fixedResult);
    expect(output).toContain("<!doctype html>");
    expect(output).toContain("2 finding(s) across 5 file(s)");
    expect(output).toContain("Possible SQL injection");
    expect(output).toContain("Generated file: dist/index.js");
    expect(output).toContain("critical (1)");
    expect(output).toContain("info (1)");
  });

  it("escapes finding content to prevent HTML injection from untrusted repository content", () => {
    const maliciousResult: ScanResult = {
      ...fixedResult,
      findings: [
        {
          ...findings[0]!,
          title: "<script>alert(1)</script>",
          description: "\"><img src=x onerror=alert(1)>",
        },
      ],
    };
    const output = htmlExporter.export(maliciousResult);
    // No unescaped tag delimiters from untrusted content may reach the output — that's what
    // would let a payload break out of text content and execute.
    expect(output).not.toContain("<script>");
    expect(output).not.toContain("<img ");
    expect(output).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(output).toContain("&lt;img src=x onerror=alert(1)&gt;");
  });
});
