import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { Diagnostic, Evidence, EvidenceId, Finding, FindingId, ScanResult } from "../../packages/core/src/index.js";
import { SCAN_RESULT_SCHEMA_VERSION } from "../../packages/core/src/index.js";
import { htmlExporter, jsonExporter, sarifExporter } from "../../packages/cli/src/exporters/index.js";
import { renderHtmlReport } from "../../packages/cli/src/exporters/html.js";

const findings: readonly Finding[] = [
  {
    id: "f-1" as FindingId,
    ruleId: "security/sql-injection-raw-query",
    category: "security",
    severity: "critical",
    confidence: 0.92,
    status: "likely",
    title: "Possible SQL injection",
    description: "Untrusted input flows into a raw SQL query.",
    locations: [{ fileId: "src/db.ts" as never, path: "src/db.ts", range: { start: { offset: 10, line: 4, column: 2 }, end: { offset: 20, line: 4, column: 12 } } }],
    evidenceIds: [],
    correlatedFindingIds: [],
  },
  {
    id: "f-2" as FindingId,
    ruleId: "quality/generated-file-count",
    category: "quality",
    severity: "info",
    confidence: 1,
    status: "confirmed",
    title: "Generated file: dist/index.js",
    description: "dist/index.js was classified as generated by repository discovery.",
    locations: [{ fileId: "dist/index.js" as never, path: "dist/index.js" }],
    evidenceIds: [],
    correlatedFindingIds: [],
  },
];

const fixedResult: ScanResult = {
  schemaVersion: SCAN_RESULT_SCHEMA_VERSION,
  scan: {
    id: "scan-1" as never,
    projectId: "project-1",
    profile: "minimal",
    mode: "full",
    status: "completed",
    analyzersRun: ["security/sql-injection-raw-query", "quality/generated-file-count"],
    findingIds: findings.map((f) => f.id),
    timing: { startedAt: "2026-01-01T00:00:00.000Z", finishedAt: "2026-01-01T00:00:01.000Z", durationMs: 1000 },
  },
  findings,
  evidence: [],
  diagnostics: [],
  summary: {
    totalFindings: 2,
    findingsBySeverity: { critical: 1, info: 1 },
    findingsByCategory: { security: 1, quality: 1 },
    filesAnalyzed: 5,
    analyzersRun: ["security/sql-injection-raw-query", "quality/generated-file-count"],
  },
};

describe("jsonExporter", () => {
  it("round-trips the ScanResult exactly", () => {
    const output = jsonExporter.export(fixedResult);
    expect(JSON.parse(output)).toEqual(fixedResult);
  });
});

describe("sarifExporter", () => {
  it("produces a structurally valid SARIF 2.1.0 log for the fields we emit", () => {
    const output = sarifExporter.export(fixedResult);
    const sarif = JSON.parse(output);

    expect(sarif.version).toBe("2.1.0");
    expect(typeof sarif.$schema).toBe("string");
    expect(sarif.runs).toHaveLength(1);

    const run = sarif.runs[0];
    expect(run.tool.driver.name).toBe("codegraph-scan");
    expect(run.tool.driver.rules.map((r: { id: string }) => r.id).sort()).toEqual(
      ["quality/generated-file-count", "security/sql-injection-raw-query"].sort(),
    );
    const sqlRule = run.tool.driver.rules.find((r: { id: string }) => r.id === "security/sql-injection-raw-query");
    expect(sqlRule.shortDescription.text).toBe("Possible SQL injection");
    expect(sqlRule.properties.category).toBe("security");

    expect(run.results).toHaveLength(2);
    const [sqlResult] = run.results;
    expect(sqlResult.ruleId).toBe("security/sql-injection-raw-query");
    expect(sqlResult.level).toBe("error"); // critical -> error
    expect(sqlResult.message.text).toBe(findings[0]?.description);
    expect(sqlResult.locations[0].physicalLocation.artifactLocation.uri).toBe("src/db.ts");
    // 0-based SourcePosition.line 4 -> 1-based SARIF startLine 5
    expect(sqlResult.locations[0].physicalLocation.region.startLine).toBe(5);
    expect(sqlResult.locations[0].physicalLocation.region.startColumn).toBe(3);

    const [, infoResult] = run.results;
    expect(infoResult.level).toBe("none"); // info -> none
    expect(infoResult.locations[0].physicalLocation.region).toBeUndefined();
  });
});

describe("htmlExporter", () => {
  it("renders a self-contained page grouping findings by severity", () => {
    const output = htmlExporter.export(fixedResult);
    expect(output).toContain("<!doctype html>");
    expect(output).toContain(">2<");
    expect(output).toContain("Total findings");
    expect(output).toContain(">5<");
    expect(output).toContain("Files analyzed");
    expect(output).toContain("Possible SQL injection");
    expect(output).toContain("Generated file: dist/index.js");
    expect(output).toMatch(/sev-chip-critical[\s\S]*?<span class="sev-chip-count">1<\/span>/);
    expect(output).toMatch(/sev-chip-info[\s\S]*?<span class="sev-chip-count">1<\/span>/);
    // Quality gate fails on any critical finding, independent of --fail-on (Section 43 semantics).
    expect(output).toContain("gate-fail");
    expect(output).toContain("Failed");
  });

  it("escapes finding content to prevent HTML injection from untrusted repository content", () => {
    const maliciousResult: ScanResult = {
      ...fixedResult,
      findings: [
        {
          ...findings[0]!,
          title: "<script>alert(1)</script>",
          description: "\"><img src=x onerror=alert(1)>",
        },
      ],
    };
    const output = htmlExporter.export(maliciousResult);
    // The malicious payload itself must never reach the output unescaped — that's what would let
    // it break out of text content and execute. The report's own trusted, hand-written <script>
    // block (for client-side filtering) is not what this test is about, so we assert against the
    // exact injected payload strings rather than banning "<script>"/"<img " outright.
    expect(output).not.toContain("<script>alert(1)</script>");
    expect(output).not.toContain("<img src=x onerror=alert(1)>");
    expect(output).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(output).toContain("&lt;img src=x onerror=alert(1)&gt;");
  });

  it("renders a finding's Evidence, not just its generic rule description", () => {
    const evidence: Evidence = {
      id: "ev-1" as EvidenceId,
      kind: "ast-pattern",
      summary: "Raw string concatenation with request.query.id passed to db.query(...)",
      locations: [{ fileId: "src/db.ts" as never, path: "src/db.ts", range: { start: { offset: 0, line: 9, column: 0 }, end: { offset: 5, line: 9, column: 5 } } }],
      confidence: 0.9,
    };
    const resultWithEvidence: ScanResult = {
      ...fixedResult,
      findings: [{ ...findings[0]!, evidenceIds: [evidence.id] }, findings[1]!],
      evidence: [evidence],
    };
    const output = htmlExporter.export(resultWithEvidence);
    expect(output).toContain("Raw string concatenation with request.query.id passed to db.query(...)");
    expect(output).toContain("src/db.ts:10");
  });

  it("renders diagnostics (parse errors, skipped files) in their own section", () => {
    const diagnostics: readonly Diagnostic[] = [
      {
        code: "FILE_SKIPPED_SIZE_LIMIT",
        severity: "warning",
        message: "File exceeds the 5 MB parse limit and was skipped.",
        source: "parser",
        filePath: "vendor/huge-bundle.js",
      },
    ];
    const resultWithDiagnostics: ScanResult = { ...fixedResult, diagnostics };
    const output = htmlExporter.export(resultWithDiagnostics);
    expect(output).toMatch(/Diagnostics <span class="section-count">1<\/span>/);
    expect(output).toContain("FILE_SKIPPED_SIZE_LIMIT");
    expect(output).toContain("File exceeds the 5 MB parse limit and was skipped.");
    expect(output).toContain("vendor/huge-bundle.js");
  });

  it("shows an explicit empty state when there are no diagnostics", () => {
    const output = htmlExporter.export(fixedResult);
    expect(output).toMatch(/Diagnostics <span class="section-count">0<\/span>/);
    expect(output).toContain("No diagnostics");
  });

  it("groups findings into per-category sections with a sidebar nav", () => {
    const output = htmlExporter.export(fixedResult);
    expect(output).toContain('id="cat-security"');
    expect(output).toContain('id="cat-quality"');
    expect(output).toContain('data-nav-target="cat-security"');
    expect(output).toContain('data-nav-target="cat-quality"');
  });

  describe("with rootPath (source-code snippets)", () => {
    let root: string;

    beforeEach(() => {
      root = mkdtempSync(join(tmpdir(), "codegraph-scan-html-test-"));
      mkdirSync(join(root, "src"), { recursive: true });
      // findings[0]'s location is src/db.ts, range.start.line 4 (0-based) — put the "bad" line
      // at index 4 so the rendered snippet's highlighted line is exactly the query line below.
      writeFileSync(
        join(root, "src", "db.ts"),
        ["import { pool } from './pool';", "", "export function run(id: string) {", "  // build query", "  return pool.query(`SELECT * FROM t WHERE id = ${id}`);", "}", ""].join("\n"),
      );
    });

    afterEach(() => {
      rmSync(root, { recursive: true, force: true });
    });

    it("embeds a real source snippet around the finding's location", () => {
      const output = renderHtmlReport(fixedResult, { rootPath: root });
      expect(output).toContain('<div class="finding-code">');
      expect(output).toContain("SELECT * FROM t WHERE id");
      expect(output).toContain("code-line-highlight");
    });

    it("never throws and omits the snippet when the file doesn't exist", () => {
      const missingFileResult: ScanResult = {
        ...fixedResult,
        findings: [{ ...findings[0]!, locations: [{ ...findings[0]!.locations[0]!, path: "does/not/exist.ts" }] }, findings[1]!],
      };
      expect(() => renderHtmlReport(missingFileResult, { rootPath: root })).not.toThrow();
      const output = renderHtmlReport(missingFileResult, { rootPath: root });
      expect(output).not.toContain('<div class="finding-code">');
    });

    it("omits snippets entirely when no rootPath is given (the export command's re-format path)", () => {
      const output = htmlExporter.export(fixedResult);
      expect(output).not.toContain('<div class="finding-code">');
    });
  });
});
