import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type {
  Analyzer,
  AnalyzerConfig,
  AnalyzerContext,
  AnalyzerRegistry,
  Finding,
  FindingId,
} from "../../packages/core/src/index.js";
import { AnalyzerClient } from "../../packages/core/src/index.js";
import { projectModelDiscoverer } from "../../packages/project-model/src/index.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_ROOT = path.resolve(__dirname, "../../fixtures/project-model");

class InMemoryRegistry implements AnalyzerRegistry {
  private readonly analyzers = new Map<string, Analyzer>();
  register(analyzer: Analyzer): void {
    this.analyzers.set(analyzer.id, analyzer);
  }
  get(id: string): Analyzer | undefined {
    return this.analyzers.get(id);
  }
  list(): readonly Analyzer[] {
    return [...this.analyzers.values()];
  }
  listByCategory(category: Analyzer["capabilities"]["category"]): readonly Analyzer[] {
    return this.list().filter((a) => a.capabilities.category === category);
  }
}

/** A trivial quality analyzer that flags every `generated`-classified file — proves analyzers can
 *  read real discovery output through `AnalyzerContext.project` without any special-casing. */
const generatedFileAnalyzer: Analyzer = {
  id: "quality/generated-file-count",
  name: "Generated File Count",
  version: "0.0.0",
  capabilities: { category: "quality" },
  supports: () => true,
  async analyze(context: AnalyzerContext) {
    const generatedFiles = context.project.files.filter((f) => f.classification === "generated");
    const findings: Finding[] = generatedFiles.map((file, index) => ({
      id: `generated-${index}` as FindingId,
      ruleId: "quality/generated-file-count",
      category: "quality",
      severity: "info",
      confidence: 1,
      status: "confirmed",
      title: `Generated file: ${file.path}`,
      description: `${file.path} was classified as generated by repository discovery.`,
      locations: [{ fileId: file.id, path: file.path }],
      evidenceIds: [],
      correlatedFindingIds: [],
    }));
    return {
      analyzerId: "quality/generated-file-count",
      findings,
      evidence: [],
      diagnostics: [],
      durationMs: 0,
    };
  },
};

function configFor(root: string): AnalyzerConfig {
  return {
    root,
    profile: "minimal",
    ignore: { patterns: [], respectGitignore: true },
    incremental: { enabled: false },
    sandbox: { enabled: true, networkAccess: false },
  };
}

describe("Phase 1 end-to-end: real discovery through the full ScanEngine lifecycle", () => {
  it("discovers the node-express fixture and runs a real analyzer over it, with zero generated files", async () => {
    const root = path.join(FIXTURES_ROOT, "node-express");
    const registry = new InMemoryRegistry();
    registry.register(generatedFileAnalyzer);

    const client = new AnalyzerClient({
      config: configFor(root),
      registry,
      strategies: {
        discoverer: projectModelDiscoverer,
        indexer: { index: async (project) => ({ project, graphs: {} }) },
      },
    });

    const result = await client.scan();

    expect(result.scan.status).toBe("completed");
    expect(result.scan.analyzersRun).toEqual(["quality/generated-file-count"]);
    expect(result.summary.filesAnalyzed).toBeGreaterThan(0);
    expect(result.findings).toHaveLength(0);
  });

  it("discovers the generated-code fixture end-to-end and reports its generated files as findings", async () => {
    const root = path.join(FIXTURES_ROOT, "generated-code");
    const registry = new InMemoryRegistry();
    registry.register(generatedFileAnalyzer);

    const client = new AnalyzerClient({
      config: configFor(root),
      registry,
      strategies: {
        discoverer: projectModelDiscoverer,
        indexer: { index: async (project) => ({ project, graphs: {} }) },
      },
    });

    const result = await client.scan();

    expect(result.scan.status).toBe("completed");
    const generatedPaths = result.findings.map((f) => f.locations[0]?.path).sort();
    expect(generatedPaths).toEqual(["dist/index.js", "src/api.generated.ts"]);
    expect(result.summary.totalFindings).toBe(2);
    expect(result.summary.findingsByCategory["quality"]).toBe(2);
  });
});
